@echo off
rem IPED processing launcher (Java 21) - fallback for iped.exe.
rem Runs iped.jar with the JRE bundled under jre/, avoiding any Java found on
rem the system. iped.exe (generated by launch4j, already pointed at the bundled
rem jre/) is the primary launcher; keep this .bat as a fallback for environments
rem where the .exe was not generated or cannot be used.
setlocal
set "IPED_HOME=%~dp0"
rem -Djava.security.manager=allow is propagated to the forked JVM, where IPED
rem installs a SecurityManager (blocked by default on Java 18+).
"%IPED_HOME%jre\bin\java.exe" -Djava.security.manager=allow -jar "%IPED_HOME%iped.jar" %*
